import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Pizzas
  {
    id: 1,
    name: 'Margherita Pizza',
    description: 'Classic cheese and tomato pizza.',
    price: 12.99,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/102/400/300',
  },
  {
    id: 2,
    name: 'Pepperoni Pizza',
    description: 'Classic pizza with pepperoni slices.',
    price: 14.99,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/103/400/300',
  },
  {
    id: 3,
    name: 'Veggie Supreme Pizza',
    description: 'Loaded with fresh vegetables.',
    price: 15.99,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/104/400/300',
  },
  {
    id: 10,
    name: 'BBQ Chicken Pizza',
    description: 'Tangy BBQ sauce, grilled chicken, and red onions.',
    price: 16.99,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/105/400/300',
  },
  {
    id: 11,
    name: 'Hawaiian Pizza',
    description: 'A tropical delight with ham and pineapple.',
    price: 15.49,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/106/400/300',
  },
  {
    id: 16,
    name: 'Meat Lover\'s Pizza',
    description: 'Packed with pepperoni, sausage, ham, and bacon.',
    price: 18.99,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/107/400/300',
  },
  {
    id: 17,
    name: 'Four Cheese Pizza',
    description: 'A blend of mozzarella, provolone, parmesan, and gorgonzola.',
    price: 16.49,
    category: 'Pizza',
    imageUrl: 'https://picsum.photos/id/108/400/300',
  },
  
  // Burgers
  {
    id: 4,
    name: 'Classic Beef Burger',
    description: 'A juicy beef patty with lettuce and tomato.',
    price: 9.99,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/201/400/300',
  },
  {
    id: 5,
    name: 'Chicken Burger',
    description: 'Grilled chicken breast with mayo.',
    price: 8.99,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/202/400/300',
  },
  {
    id: 6,
    name: 'Veggie Burger',
    description: 'A delicious plant-based patty.',
    price: 8.49,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/203/400/300',
  },
  {
    id: 12,
    name: 'Bacon Cheeseburger',
    description: 'Topped with crispy bacon and melted cheese.',
    price: 11.99,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/204/400/300',
  },
  {
    id: 13,
    name: 'Mushroom Swiss Burger',
    description: 'Sautéed mushrooms and melted Swiss cheese.',
    price: 11.49,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/205/400/300',
  },
  {
    id: 18,
    name: 'Double Cheeseburger',
    description: 'Two juicy beef patties with double the cheese.',
    price: 13.99,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/206/400/300',
  },
  {
    id: 19,
    name: 'Spicy Chicken Burger',
    description: 'Crispy chicken breast with a fiery chili sauce.',
    price: 10.99,
    category: 'Burger',
    imageUrl: 'https://picsum.photos/id/207/400/300',
  },

  // Drinks
  {
    id: 7,
    name: 'Cola',
    description: 'Refreshing classic cola.',
    price: 2.5,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/301/400/300',
  },
  {
    id: 8,
    name: 'Lemonade',
    description: 'Freshly squeezed lemonade.',
    price: 3.0,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/302/400/300',
  },
  {
    id: 9,
    name: 'Iced Tea',
    description: 'Chilled iced tea.',
    price: 2.75,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/303/400/300',
  },
  {
    id: 14,
    name: 'Orange Juice',
    description: 'Freshly squeezed orange juice.',
    price: 3.50,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/304/400/300',
  },
  {
    id: 15,
    name: 'Water Bottle',
    description: 'Chilled spring water.',
    price: 1.50,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/305/400/300',
  },
  {
    id: 20,
    name: 'Vanilla Milkshake',
    description: 'Creamy and classic vanilla milkshake.',
    price: 4.50,
    category: 'Drink',
    imageUrl: 'https://picsum.photos/id/306/400/300',
  },
];